### ISSUE TITLE
Design Initial Architecture

### ISSUE THREAD

**Issue by awang9999** [CornellDataScience/MathSearch#2]
Develop the overall architecture of the application. Must include plans for developing the front end, intermediary layer, and back end/ML model. Will require input from experienced members of the team. The follow up task to this will be deploying starter environments for each component so people can start pushing code and working.

**Comment by emerisly** [comment]
<img width="1237" alt="image" src="https://github.com/CornellDataScience/MathSearch/assets/44758321/ffc4efe0-34ca-43c9-947f-d469ca8e3c4f">
