### ISSUE TITLE
Set up deployment pipeline using Github Actions to push to server hosting the front end

### ISSUE THREAD

**Issue by awang9999** [CornellDataScience/MathSearch#4]
Develop an automatic CI/CD pipeline to make pushing changes to the front end to production easy.

**Comment by emerisly** [comment]
See frontend readme at https://github.com/CornellDataScience/MathSearch/blob/front-end/front-end/README.md
Basically run `npm run build` (react build) and `sudo systemctl restart nginx` (update deployment)
