### ISSUE TITLE
Draw bonding box on pdf - size mismatch / info lost

### ISSUE THREAD

**Issue by emerisly** [CornellDataScience/MathSearch#44]
For pages with no results, the most computing-efficient way causes:
- size mismatch (there are fixes, but didn't find an easy fix yet), see figure 1
- sidebar information lost (bookmark), compare to figure 2 with sidebar information
The good news is still able to highlight and copy text

Can Frontend React confirm if these issues are fine?

Right now, 90KB file take 1 second to render, 2.6MB file takes 5 seconds to render.
We can try improve after MVP.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/44758321/228105314-d6596b18-bbb9-4723-8a25-a7587be8d7b8.png">

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/44758321/228106486-cbd1d478-867f-4049-8e1d-e8bd9af55991.png">

**Comment by jasozh** [comment]
I think losing bookmarks is fine since the results page doesn't use bookmarks anywhere. The size mismatch is definitely an issue but not a breaking bug; frontend should still be able to render the PDF and navigate to the page the result is on.

**Comment by emerisly** [comment]
I've added a not-perfect but somewhat working patch
:) 
<img width="805" alt="image" src="https://user-images.githubusercontent.com/44758321/228773294-5d0dfdd1-eb5b-43c0-bf04-3e9fd6ab79d1.png">

**Comment by emerisly** [comment]
Done!
